---
- name: Wait for NGINX ALB to respond
  ansible.builtin.uri:
    url: "http://{{ nginx_alb_dns }}"
    method: GET
    status_code: [200]
  register: nginx_health
  retries: 20
  delay: 10
  until: nginx_health.status == 200
